[book]
authors = ["David Thrane Christiansen"]
translators = ["Oling Cat", "Qiu233", "JiechengZhao"]
language = "zh-CN"
multilingual = true
src = "src"
title = "Lean 函数式编程"

[build]

[preprocessor.buildexamples]
command = "python -X utf8 scripts/build-examples.py"
before = ["leanexample", "commands"]

[preprocessor.leanexample]
command = "python -X utf8 scripts/example.py"

[preprocessor.commands]
command = "python -X utf8 scripts/projects.py"

[preprocessor.leanversion]
command = "python -X utf8 scripts/lean-version.py"

# [preprocessor.trimspace]
# command = "python -X utf8 scripts/trim-space.py"

[output.html]
additional-css = ["custom.css", "pygments.css"]
additional-js = ["custom.js"]
mathjax-support = true
site-url = "/fp-lean-zh/"
git-repository-url = "https://github.com/Lean-zh/fp-lean-zh"
edit-url-template = "https://github.com/Lean-zh/fp-lean-zh/edit/master/functional-programming-lean/{path}"

#[output.pandoc]
#command = "python -X utf8 ../../scripts/one-markdown.py"

[output.fancywordcount]
command = "python -X utf8 ../../scripts/wc.py"
